(() => {
'use strict';
const API='https://api.finmindtrade.com/api/v4/data';
const WATCH_KEY='kaiV4WatchlistV1', CACHE_KEY='kaiV4CustomCacheV1';
let rows=[], period='D', selectedDate='', activeTab='radar', currentStock=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=(v,d=1)=>v==null||Number.isNaN(Number(v))?'-':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const pct=v=>v==null?'-':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`;
const net=v=>v==null?'-':`${Number(v)>=0?'+':''}${(Number(v)/1e8).toFixed(2)}億`;
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const pname=p=>p==='D'?'日線':p==='W'?'週線':'月線';
function signal(s){const m={'偏多／可研究':['g','🟢 偏多／可研究'],'等待站回20MA':['y','🟡 等待站回20MA'],'過熱':['o','🟠 過熱'],'超跌觀察':['b','🔵 超跌觀察'],'不追高':['r','🔴 不追高'],'中性':['','⚪ 中性']};const x=m[s]||m['中性'];return `<span class="badge ${x[0]}">${x[1]}</span>`}
function dot(s){const m={'偏多／可研究':'green','等待站回20MA':'yellow','過熱':'orange','超跌觀察':'blue','不追高':'red','中性':'gray'};return `<span class="dot ${m[s]||'gray'}"></span>`}
function ema(a,n){if(a.length<n)return null;const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function technical(h){const c=h.map(x=>+x.close),v=h.map(x=>+x.volume||0);if(!c.length)return{};const sma=k=>c.length>=k?mean(c.slice(-k)):null,ma5=sma(5),ma20=sma(20),ma60=sma(60),v20=v.length>=20?mean(v.slice(-20)):null,vr=v20?mean(v.slice(-5))/v20:null;let g=[],l=[];for(let i=1;i<c.length;i++){const d=c[i]-c[i-1];g.push(Math.max(d,0));l.push(Math.max(-d,0))}let rsi=null;if(g.length>=14){const ag=mean(g.slice(-14)),al=mean(l.slice(-14));rsi=al===0?100:100-100/(1+ag/al)}let hist=null;if(c.length>=35){const m=c.map((_,i)=>ema(c.slice(0,i+1),12)-ema(c.slice(0,i+1),26)).filter(Number.isFinite),es=ema(m,9);hist=es==null?null:m.at(-1)-es}const price=c.at(-1),gap=ma20?(price/ma20-1)*100:null,trend=(price>ma20?1:0)+(price>ma60?1:0)+(ma20>ma60?1:0)+(rsi!=null&&rsi>=50&&rsi<=70?1:rsi>75?-1:0)+(hist!=null&&hist>0?1:0);let ts=Math.max(35,Math.min(98,65+trend*6));if(gap>12)ts=Math.max(35,ts-8);if(gap<-8)ts=Math.max(35,ts-4);const sig=rsi>80?'過熱':rsi<35&&price<ma20?'超跌觀察':price<ma20?'等待站回20MA':trend>=3?'偏多／可研究':'中性';return{price,ma5,ma20,ma60,ma20_gap_pct:gap,rsi14:rsi,macd_hist:hist,volume_ratio_5d_20d:vr,technical_score:ts,technical_signal:sig,date:h.at(-1)?.date}}
function histFor(r,cut){let h=(r.history||[]).filter(x=>x.date<=cut);if(period==='D')return h;const g={};h.forEach(x=>{const d=new Date(x.date+'T00:00:00');let k;if(period==='W'){const day=d.getDay()||7;d.setDate(d.getDate()-day+1);k=d.toISOString().slice(0,10)}else k=x.date.slice(0,7);(g[k]??=[]).push(x)});return Object.keys(g).sort().map(k=>{const a=g[k],z=a.at(-1);return{date:z.date,close:z.close,volume:a.reduce((s,x)=>s+(+x.volume||0),0)}})}
function score(r){let b=r.base??70,ind=r.industry_score??Math.min(98,b+8),val=r.valuation_score??Math.max(45,b-8),chip=r.chips_score??70,techs=r.technical_score??Math.min(96,b+4),fund=r.fundamental_score??Math.min(96,b+4);if(r.revenue_yoy!=null)fund=Math.max(45,Math.min(98,fund+(r.revenue_yoy>10?5:r.revenue_yoy>0?2:-3)));if(r.eps_ttm>0)fund=Math.min(98,fund+2);if(r.pe>0)val=Math.max(45,Math.min(98,val+(r.pe<20?4:r.pe>45?-5:0)));return{...r,industry_score:ind,valuation_score:val,chips_score:chip,technical_score:techs,fundamental_score:fund,score:Math.round(ind*.25+fund*.25+val*.2+chip*.15+techs*.15)}}
function effective(){const d=[...new Set(rows.flatMap(r=>(r.history||[]).map(x=>x.date)))].sort();if(!d.length)return selectedDate;return d.filter(x=>x<=selectedDate).at(-1)||d[0]}
function view(r){const h=histFor(r,effective());if(!h.length)return score({...r,price:null,pct:null});const t=technical(h),i=h.length-1;return score({...r,...t,pct:i?((h[i].close/h[i-1].close)-1)*100:null})}
function renderSpark(h,w=180,hgt=48){if(!h?.length)return '';const a=h.map(x=>+x.close),mn=Math.min(...a),mx=Math.max(...a),rg=mx-mn||1;const pts=a.map((v,i)=>`${(i/(a.length-1||1))*w},${hgt-((v-mn)/rg)*(hgt-4)-2}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${hgt}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`}
function tableHTML(data,manage=false){return data.map((x,i)=>`<tr><td><div class="conclusion">${dot(x.technical_signal)}${signal(x.technical_signal)}</div></td><td><b>${esc(x.name)}</b></td><td>${esc(x.id)}</td><td>${esc(x.category||'')}</td><td>${n(x.price)}</td><td class="${x.pct>0?'up':x.pct<0?'down':'flat'}">${pct(x.pct)}</td><td><b>${n(x.score,0)}</b></td><td>${n(x.industry_score,0)}</td><td>${n(x.fundamental_score,0)}</td><td>${n(x.valuation_score,0)}</td><td>${n(x.chips_score,0)}</td><td>${n(x.technical_score,0)}</td><td>${n(x.pe,2)}</td><td>${n(x.eps_ttm,2)}</td><td>${x.revenue==null?'-':n(x.revenue/1e8,2)+'億'}</td><td>${pct(x.revenue_yoy)}</td><td>${net(x.foreign_20d_net)}</td><td>${net(x.trust_20d_net)}</td><td>${net(x.institution_20d_net)}</td><td>${n(x.ma5,2)}</td><td>${n(x.ma20,2)}</td><td>${n(x.ma60,2)}</td><td>${pct(x.ma20_gap_pct)}</td><td>${n(x.rsi14,1)}</td><td>${n(x.macd_hist,3)}</td><td>${x.volume_ratio_5d_20d==null?'-':n(x.volume_ratio_5d_20d,2)+'x'}</td>${manage?`<td><button class="mini" data-remove="${esc(x.id)}">移除</button></td>`:''}</tr>`).join('')}
function baseTable(title,manage=false){return `<div class="card"><div class="section-head"><h2>${title}</h2><span class="muted">結論 → 基本面 → 估值 → 籌碼 → 技術</span></div><div class="tablewrap"><table><thead><tr><th>結論</th><th>股票</th><th>代號</th><th>類別</th><th>最新價</th><th>漲跌%</th><th>評分</th><th>產業</th><th>基本面</th><th>估值</th><th>籌碼</th><th>技術</th><th>PE</th><th>EPS</th><th>月營收</th><th>YoY</th><th>外資20日</th><th>投信20日</th><th>法人20日</th><th>MA5</th><th>MA20</th><th>MA60</th><th>距20MA</th><th>RSI</th><th>MACD柱</th><th>量比</th>${manage?'<th>管理</th>':''}</tr></thead><tbody id="mainBody"></tbody></table></div></div>`}
function radar(){const eff=effective(),all=rows.map(view),f=$('categoryFilter').value,data=all.filter(x=>f==='all'||x.category===f),v=data.filter(x=>x.pct!=null),avg=mean(v.map(x=>x.pct)),best=[...v].sort((a,b)=>b.pct-a.pct)[0],weak=[...v].sort((a,b)=>a.pct-b.pct)[0];$('content').innerHTML=`<div class="toolbar"><div>📅 <input id="datePicker" type="date" value="${eff}" min="${[...new Set(rows.flatMap(r=>(r.history||[]).map(x=>x.date)))].sort()[0]||''}" max="${eff}"></div><button id="prev">← 前一交易日</button><button id="next">下一交易日 →</button><button id="today">今天</button><div class="periods"><button class="pbtn ${period==='D'?'on':''}" data-p="D">日</button><button class="pbtn ${period==='W'?'on':''}" data-p="W">週</button><button class="pbtn ${period==='M'?'on':''}" data-p="M">月</button></div><select id="categoryFilter"><option value="all">全部類股</option>${[...new Set(rows.map(x=>x.category))].filter(Boolean).map(x=>`<option ${f===x?'selected':''}>${esc(x)}</option>`).join('')}</select><button id="reload">↻ 更新</button><button id="csv">⬇ CSV</button><span class="status">資料基準 ${eff}｜${pname(period)}</span></div><div class="metrics"><div><b>${v.length}/${data.length}</b><small>有價格資料</small></div><div><b>${pct(avg)}</b><small>${pname(period)}平均</small></div><div><b>${best?esc(best.name)+' '+pct(best.pct):'-'}</b><small>最強</small></div><div><b>${weak?esc(weak.name)+' '+pct(weak.pct):'-'}</b><small>最弱</small></div><div><b>${data.filter(x=>x.technical_signal==='偏多／可研究').length} 檔</b><small>偏多／可研究</small></div></div>${baseTable(`🎯 AI 產業雷達 V4.0｜${pname(period)}｜${eff}`)}<div class="card"><div class="section-head"><h2>⭐ 研究優先</h2><span class="muted">綜合評分 Top 6</span></div><div class="cards">${[...data].sort((a,b)=>b.score-a.score).slice(0,6).map(x=>`<div class="stockcard"><div class="stock-title"><b>${esc(x.name)}</b><span>${x.id}</span></div><div class="score">${x.score}<small>/100</small></div>${signal(x.technical_signal)}<p>${esc(x.logic||'')}</p><div class="sparkline">${renderSpark(histFor(x,eff))}</div><p>價格 ${n(x.price)}｜RSI ${n(x.rsi14,1)}｜距20MA ${pct(x.ma20_gap_pct)}</p></div>`).join('')}</div></div>`;const body=$('mainBody');body.innerHTML=tableHTML(data.sort((a,b)=>b.score-a.score));bindRadar();}
function bindRadar(){ $('datePicker').onchange=e=>{selectedDate=e.target.value;radar()};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('today').onclick=()=>{selectedDate=[...new Set(rows.flatMap(r=>(r.history||[]).map(x=>x.date)))].sort().at(-1)||selectedDate;radar()};document.querySelectorAll('.pbtn').forEach(b=>b.onclick=()=>{period=b.dataset.p;radar()});$('categoryFilter').onchange=radar;$('reload').onclick=loadData;$('csv').onclick=downloadCSV}
function move(dir){const d=[...new Set(rows.flatMap(r=>(r.history||[]).map(x=>x.date)))].sort(),i=d.indexOf(effective());if(i>=0&&d[i+dir]){selectedDate=d[i+dir];radar()}}
function ranking(){const a=rows.map(view).sort((x,y)=>(y.score-y.technical_score*.1+y.technical_score*.1)-(x.score-x.technical_score*.1+x.technical_score*.1));const picks=a.filter(x=>x.technical_signal==='偏多／可研究'||x.technical_signal==='超跌觀察').sort((x,y)=>{const sx=y.score+y.chips_score*.1+y.valuation_score*.1+Math.max(0,10-Math.abs(y.ma20_gap_pct||0));const tx=x.score+x.chips_score*.1+x.valuation_score*.1+Math.max(0,10-Math.abs(x.ma20_gap_pct||0));return sx-tx});$('content').innerHTML=`<div class="hero"><div><span class="eyebrow">DAILY AI RANKING</span><h2>📈 AI 買點排行</h2><p>不是「推薦買進」，而是把<strong>基本面、估值、法人、技術位置</strong>濃縮成值得研究的優先順序。</p></div><div class="hero-score">${picks.length}<small>可研究標的</small></div></div><div class="rankgrid">${picks.slice(0,10).map((x,i)=>`<div class="rankcard"><div class="rankno">#${i+1}</div><div class="rankmain"><h3>${esc(x.name)} <small>${x.id}</small></h3>${signal(x.technical_signal)}<div class="rankbar"><span style="width:${Math.min(100,x.score)}%"></span></div><div class="rankmeta"><b>${x.score}</b> 綜合｜技術 ${n(x.technical_score,0)}｜估值 ${n(x.valuation_score,0)}｜籌碼 ${n(x.chips_score,0)}</div><p>${x.ma20_gap_pct!=null?(x.ma20_gap_pct<0?'位於20MA下方，等待轉強。':x.ma20_gap_pct>8?'已偏離20MA，避免追價。':'接近20MA，風險報酬較平衡。'):''}</p><button data-diagnose="${x.id}">查看個股診斷</button></div></div>`).join('')}</div>`;document.querySelectorAll('[data-diagnose]').forEach(b=>b.onclick=()=>diagnose(b.dataset.diagnose))}
function getWatch(){try{return JSON.parse(localStorage.getItem(WATCH_KEY)||'[]')}catch{return[]}}function saveWatch(a){localStorage.setItem(WATCH_KEY,JSON.stringify([...new Set(a)].slice(0,50)))}
function watchlist(){const ids=getWatch(),data=rows.map(view).filter(x=>ids.includes(x.id));$('content').innerHTML=`<div class="hero"><div><span class="eyebrow">MY WATCHLIST</span><h2>👀 我的觀察名單</h2><p>最多 50 檔；收藏只存在此瀏覽器，不會寫入 GitHub。你可以從雷達或個股診斷中心加入。</p></div><div class="hero-score">${data.length}<small>/ 50</small></div></div>${baseTable('⭐ 我的觀察名單',true)}`;$('mainBody').innerHTML=data.length?tableHTML(data,true):'<tr><td colspan="28" class="empty">尚未收藏股票。到「個股診斷中心」搜尋後加入。</td></tr>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveWatch(ids.filter(x=>x!==b.dataset.remove));watchlist()})}
function diagnose(id){const x=rows.map(view).find(r=>r.id===String(id));if(!x){diagnoseCustom(String(id));return}currentStock=x;renderDiagnosis(x)}
function renderDiagnosis(x){const h=histFor(x,effective()),gap=x.ma20_gap_pct;let action=x.technical_signal==='偏多／可研究'?'可研究／分批布局':x.technical_signal==='等待站回20MA'?'等待站回20MA':x.technical_signal==='超跌觀察'?'超跌反彈觀察':x.technical_signal==='過熱'?'避免追高':'等待訊號';let risks=[];if(x.pe>45)risks.push('本益比偏高');if(x.revenue_yoy!=null&&x.revenue_yoy<0)risks.push('營收年增轉弱');if(x.chips_score<60)risks.push('法人籌碼偏弱');if(gap>12)risks.push('股價明顯偏離20MA');if(!risks.length)risks.push('目前未見明顯單一項目風險');$('content').innerHTML=`<div class="diagnose-head"><div><span class="eyebrow">STOCK DIAGNOSTIC</span><h2>🔬 ${esc(x.name)} <small>${x.id}</small></h2><div class="bigprice">${n(x.price)} <span class="${x.pct>=0?'up':'down'}">${pct(x.pct)}</span></div>${signal(x.technical_signal)} <span class="tag">建議：${action}</span></div><div class="diag-score"><span>綜合評分</span><b>${x.score}</b><small>/100</small></div></div><div class="diaggrid"><div class="card"><h3>價格趨勢</h3>${renderSpark(h,520,150)}<div class="four"><span>MA5 <b>${n(x.ma5,2)}</b></span><span>MA20 <b>${n(x.ma20,2)}</b></span><span>MA60 <b>${n(x.ma60,2)}</b></span><span>RSI <b>${n(x.rsi14,1)}</b></span></div></div><div class="card"><h3>五大因子</h3>${[['產業',x.industry_score],['基本面',x.fundamental_score],['估值',x.valuation_score],['籌碼',x.chips_score],['技術',x.technical_score]].map(a=>`<div class="factor"><span>${a[0]}</span><b>${n(a[1],0)}</b><i><em style="width:${a[1]}%"></em></i></div>`).join('')}</div></div><div class="diaggrid"><div class="card"><h3>基本面</h3><div class="statgrid"><span>PE <b>${n(x.pe,2)}</b></span><span>EPS(TTM) <b>${n(x.eps_ttm,2)}</b></span><span>月營收 <b>${x.revenue==null?'-':n(x.revenue/1e8,2)+'億'}</b></span><span>營收YoY <b>${pct(x.revenue_yoy)}</b></span></div></div><div class="card"><h3>法人籌碼</h3><div class="statgrid"><span>外資20日 <b>${net(x.foreign_20d_net)}</b></span><span>投信20日 <b>${net(x.trust_20d_net)}</b></span><span>法人20日 <b>${net(x.institution_20d_net)}</b></span><span>量比 <b>${x.volume_ratio_5d_20d==null?'-':n(x.volume_ratio_5d_20d,2)+'x'}</b></span></div></div></div><div class="card"><h3>🤖 凱爾 AI 判讀</h3><ul class="analysis"><li><b>趨勢：</b>${gap!=null?(gap>0?'股價站在20MA之上，短線結構偏強。':'股價仍在20MA下方，先觀察能否站回。'):'技術資料不足。'}</li><li><b>估值：</b>${x.pe!=null?(x.pe<20?'本益比相對友善。':x.pe>45?'本益比偏高，追價風險增加。':'估值處於中間區間。'):'缺乏PE資料。'}</li><li><b>營運：</b>${x.revenue_yoy!=null?(x.revenue_yoy>10?'營收年增明顯，基本面有支撐。':x.revenue_yoy>0?'營收仍成長，但動能普通。':'營收年增轉弱，需留意基本面。'):'營收資料不足。'}</li><li><b>籌碼：</b>${x.chips_score>=80?'法人籌碼偏正向。':x.chips_score>=65?'籌碼中性。':'法人籌碼偏弱，需控制部位。'}</li></ul></div><div class="card risk"><h3>⚠️ 風險提醒</h3><p>${risks.join('｜')}</p><p class="muted">以上為規則化量化判讀，不構成投資建議；買點、停損與部位仍應依你的風險承受度決定。</p></div>`}
function diagnosisHome(){const ids=getWatch();$('content').innerHTML=`<div class="hero"><div><span class="eyebrow">STOCK DIAGNOSTIC CENTER</span><h2>🔬 個股診斷中心</h2><p>輸入台股股號或股票名稱，先從目前雷達資料建立量化診斷；自選股則可即時向 FinMind 取得資料。</p><div class="searchline"><input id="diagInput" placeholder="例如：6186、2330、台積電、新潤"><button id="diagBtn">開始診斷</button></div></div><div class="hero-score">${ids.length}<small>已收藏</small></div></div><div class="card"><h3>快速診斷</h3><div class="quick">${rows.slice().sort((a,b)=>b.base-a.base).slice(0,8).map(x=>`<button data-q="${x.id}">${esc(x.name)} ${x.id}</button>`).join('')}</div></div>`;$('diagBtn').onclick=()=>diagnoseInput();$('diagInput').onkeydown=e=>{if(e.key==='Enter')diagnoseInput()};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>diagnose(b.dataset.q))}
function diagnoseInput(){const q=$('diagInput').value.trim();if(!q)return;const by=rows.find(x=>x.id===q)||rows.find(x=>x.name.includes(q));if(by)diagnose(by.id);else diagnoseCustom(q)}
async function api(p){const r=await fetch(API+'?'+new URLSearchParams(p),{cache:'no-store'});if(!r.ok)throw Error(`FinMind HTTP ${r.status}`);const j=await r.json();if(j.status&&j.status!==200)throw Error(j.msg||'FinMind API error');return j.data||[]}
async function resolveCustom(q){if(/^\d{4}$/.test(q))return{id:q};const info=await api({dataset:'TaiwanStockInfo'}),hit=info.find(x=>String(x.stock_id||x.id)===q)||info.find(x=>String(x.stock_name||x.name||'').includes(q));if(!hit)throw Error('找不到股票');return{id:String(hit.stock_id||hit.id),name:String(hit.stock_name||hit.name||q)}}
async function fetchCustom(s){const end=new Date().toISOString().slice(0,10),start=new Date(Date.now()-430*86400000).toISOString().slice(0,10),chipStart=new Date(Date.now()-45*86400000).toISOString().slice(0,10);const [p,per,fin,rev,chip]=await Promise.all([api({dataset:'TaiwanStockPrice',data_id:s.id,start_date:start,end_date:end}),api({dataset:'TaiwanStockPER',data_id:s.id,start_date:start,end_date:end}),api({dataset:'TaiwanStockFinancialStatements',data_id:s.id,start_date:start,end_date:end}),api({dataset:'TaiwanStockMonthRevenue',data_id:s.id,start_date:start,end_date:end}),api({dataset:'TaiwanStockInstitutionalInvestorsBuySellWide',data_id:s.id,start_date:chipStart,end_date:end})]);const hist=p.map(x=>({date:x.date,close:+x.close,volume:+(x.Trading_Volume||0)})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>a.date.localeCompare(b.date));if(!hist.length)throw Error('沒有價格資料');const t=technical(hist),prev=hist.at(-2),latest=[...per].sort((a,b)=>String(a.date).localeCompare(String(b.date))).at(-1)||{},eps=fin.filter(x=>x.type==='EPS'&&x.value!==''&&x.value!=null).map(x=>+x.value),epsTtm=eps.length?eps.slice(-4).reduce((a,b)=>a+b,0):null,rv=[...rev].sort((a,b)=>String(a.date).localeCompare(String(b.date))),lr=rv.at(-1)||{};let yoy=null;if(lr.revenue!=null){const old=rv.find(x=>+x.revenue_year===+lr.revenue_year-1&&+x.revenue_month===+lr.revenue_month);if(old?.revenue)yoy=(+lr.revenue/+old.revenue-1)*100}const ch=[...chip].sort((a,b)=>a.date.localeCompare(b.date)).slice(-20),f=ch.reduce((z,x)=>z+(+x.Foreign_Investor_buy||0)-(+x.Foreign_Investor_sell||0),0),tr=ch.reduce((z,x)=>z+(+x.Investment_Trust_buy||0)-(+x.Investment_Trust_sell||0),0),de=ch.reduce((z,x)=>z+(+(x.Dealer_self_buy||0)-+(x.Dealer_self_sell||0))+(+(x.Dealer_Hedging_buy||0)-+(x.Dealer_Hedging_sell||0)),0),inst=f+tr+de,fund=Math.max(45,Math.min(98,74+(yoy!=null?(yoy>10?5:yoy>0?2:-3):0)+(epsTtm>0?2:0))),val=Math.max(45,Math.min(98,74+(latest.PER>0?(+latest.PER<20?4:+latest.PER>45?-5:0):0))),chips=inst>0?88:68;return score({...s,name:s.name||s.id,category:'自選股',...t,pct:prev?((t.price/prev.close)-1)*100:null,industry_score:70,fundamental_score:fund,valuation_score:val,chips_score:chips,pe:latest.PER!=null?+latest.PER:null,eps_ttm:epsTtm,revenue:lr.revenue!=null?+lr.revenue:null,revenue_yoy:yoy,foreign_20d_net:f,trust_20d_net:tr,institution_20d_net:inst,history:hist})}
async function diagnoseCustom(q){$('content').innerHTML='<div class="loading card">🔄 正在向 FinMind 取得資料並計算技術、基本面、估值與籌碼…</div>';try{const s=await resolveCustom(q),cache=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}'),hit=cache[s.id];let x=hit&&Date.now()-hit.ts<15*60*1000?hit.data:await fetchCustom(s);cache[s.id]={ts:Date.now(),data:x};localStorage.setItem(CACHE_KEY,JSON.stringify(cache));currentStock=x;renderDiagnosis(x);if(confirm('是否加入「我的觀察名單」？')){saveWatch([...getWatch(),x.id]);}}catch(e){$('content').innerHTML=`<div class="card errorbox">❌ ${esc(e.message)}<br><small>若是 FinMind 暫時無法回應，請稍後再試。</small></div>`}}
function market(){const a=rows.map(view),avg=mean(a.map(x=>x.pct).filter(v=>v!=null)),green=a.filter(x=>x.technical_signal==='偏多／可研究').length,hot=a.filter(x=>x.technical_signal==='過熱').length,weak=a.filter(x=>x.technical_signal==='等待站回20MA'||x.technical_signal==='超跌觀察').length,leaders=[...a].sort((x,y)=>y.score-x.score).slice(0,5);$('content').innerHTML=`<div class="hero"><div><span class="eyebrow">MARKET INTELLIGENCE</span><h2>📰 AI 市場情報室</h2><p>目前版本以雷達資料做「量化市場情報」；新聞文字不在 GitHub Pages 內硬編，避免過期資訊冒充即時新聞。</p></div><div class="hero-score">${pct(avg)}<small>12檔平均</small></div></div><div class="metrics"><div><b>${green}</b><small>偏多</small></div><div><b>${hot}</b><small>過熱</small></div><div><b>${weak}</b><small>等待／超跌</small></div><div><b>${a.filter(x=>x.chips_score>=80).length}</b><small>籌碼偏強</small></div><div><b>${a.filter(x=>x.revenue_yoy>10).length}</b><small>營收高成長</small></div></div><div class="intelgrid"><div class="card"><h3>🔎 今日市場結論</h3><div class="intelbig">${avg>1?'偏多環境':avg<-1?'偏弱環境':'震盪環境'}</div><p>${avg>1?'多數追蹤股日線偏正，仍應區分趨勢強勢與短線過熱。':avg<-1?'整體平均偏弱，優先等待技術面止跌與法人轉強。':'市場分歧，適合以個股評分與位置挑選，而非全面追價。'}</p></div><div class="card"><h3>🏆 目前領先群</h3>${leaders.map((x,i)=>`<div class="leader"><b>#${i+1} ${esc(x.name)}</b><span>${x.score}｜${signal(x.technical_signal)}</span></div>`).join('')}</div></div><div class="card"><h3>⚠️ 今日風險雷達</h3><div class="riskchips">${a.filter(x=>x.technical_signal==='過熱'||x.ma20_gap_pct>12).map(x=>`<span>🔴 ${esc(x.name)}：${x.ma20_gap_pct>12?'偏離20MA':'過熱'}</span>`).join('')||'<span>目前沒有明顯過熱標的</span>'}</div><p class="muted">資料基準：${effective()}。此頁是量化訊號摘要，不等同即時新聞。</p></div>`}
function nav(){const tabs=[['radar','🧭 AI產業雷達'],['rank','📈 AI買點排行'],['watch','👀 我的觀察名單'],['diag','🔬 個股診斷中心'],['market','📰 市場情報室']];return `<nav class="tabs">${tabs.map(([k,t])=>`<button class="tab ${activeTab===k?'active':''}" data-tab="${k}">${t}</button>`).join('')}<button class="tab" data-tab="custom">⭐ 自選股雷達</button></nav>`}
function shell(){document.body.innerHTML=`<header><div class="head-inner"><div><h1>🧭 凱爾 AI 台股投資雷達 <span>Pro V4.0</span></h1><p>基本面 × 估值 × 籌碼 × 技術面 × AI產業趨勢｜量化投資終端</p></div><div class="updated" id="updated">資料載入中…</div></div></header><main><div id="nav"></div><div id="content"></div></main><footer>V4.0 Pro｜資料來源 FinMind｜量化分析僅供研究參考，不構成投資建議</footer>`;renderNav()}
function renderNav(){ $('nav').innerHTML=nav();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;if(activeTab==='custom')customHome();else{renderNav();if(activeTab==='radar')radar();if(activeTab==='rank')ranking();if(activeTab==='watch')watchlist();if(activeTab==='diag')diagnosisHome();if(activeTab==='market')market()}})}
function customHome(){ $('content').innerHTML=`<div class="hero"><div><span class="eyebrow">CUSTOM RADAR</span><h2>⭐ 自選股雷達</h2><p>輸入股號或股票名稱；清單保存在本機瀏覽器，最多 50 檔。首次分析會向 FinMind 取得資料，結果快取 15 分鐘。</p><div class="searchline"><input id="customInput" placeholder="例如 6186、新潤、2882、台達電"><button id="customAdd">＋ 新增並分析</button><button id="customRefresh">↻ 全部更新</button></div></div><div class="hero-score" id="customCount">0<small>/ 50</small></div></div><div class="card"><div class="section-head"><h2>自選清單</h2><span class="muted">同樣的燈號邏輯</span></div><div id="customList" class="custom-list"></div></div>`;renderCustomList();$('customAdd').onclick=addCustom;$('customRefresh').onclick=refreshCustom;$('customInput').onkeydown=e=>{if(e.key==='Enter')addCustom()}}
function getCustom(){try{return JSON.parse(localStorage.getItem('kaiV4CustomListV1')||'[]')}catch{return[]}}function saveCustom(a){localStorage.setItem('kaiV4CustomListV1',JSON.stringify([...new Map(a.map(x=>[x.id,x])).values()].slice(0,50)))}
async function addCustom(){const q=$('customInput').value.trim();if(!q)return;try{$('customAdd').disabled=true;$('customAdd').textContent='分析中…';const s=await resolveCustom(q);const x=await fetchCustom(s),a=getCustom().filter(z=>z.id!==x.id);saveCustom([...a,{id:x.id,name:x.name}]);const w=getWatch();saveWatch([...w,x.id]);renderCustomList()}catch(e){alert(e.message)}finally{$('customAdd').disabled=false;$('customAdd').textContent='＋ 新增並分析'}}
async function refreshCustom(){const list=getCustom();if(!list.length)return;const box=$('customList');box.innerHTML='<div class="loading">🔄 正在更新自選股…</div>';for(const s of list){try{const x=await fetchCustom(s),cache=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}');cache[x.id]={ts:Date.now(),data:x};localStorage.setItem(CACHE_KEY,JSON.stringify(cache))}catch{}}renderCustomList()}
async function renderCustomList(){const list=getCustom();$('customCount').innerHTML=`${list.length}<small>/ 50</small>`;if(!list.length){$('customList').innerHTML='<div class="empty">尚未加入自選股。</div>';return}const cache=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}');let data=list.map(s=>cache[s.id]?.data).filter(Boolean);$('customList').innerHTML=data.length?`<div class="tablewrap">${baseTable('⭐ 自選股量化雷達',true)}</div>`:'<div class="loading">尚未有分析快取，請按「全部更新」。</div>';if(data.length){$('mainBody').innerHTML=tableHTML(data,true);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveCustom(list.filter(x=>x.id!==b.dataset.remove));saveWatch(getWatch().filter(x=>x!==b.dataset.remove));renderCustomList()})}}
function downloadCSV(){const data=rows.map(view),head=['日期','週期','結論','股票','代號','價格','漲跌%','評分','PE','EPS','營收YoY','RSI','MA20','距20MA','MACD柱'];const lines=[head.join(','),...data.map(x=>[effective(),pname(period),x.technical_signal,x.name,x.id,x.price??'',x.pct??'',x.score,x.pe??'',x.eps_ttm??'',x.revenue_yoy??'',x.rsi14??'',x.ma20??'',x.ma20_gap_pct??'',x.macd_hist??''].join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'}));a.download=`kai-ai-radar-${period}-${effective()}.csv`;a.click()}
async function loadData(){try{const r=await fetch(`data/latest.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`資料 HTTP ${r.status}`);const j=await r.json();rows=(j.stocks||[]).map(score);const dates=[...new Set(rows.flatMap(r=>(r.history||[]).map(x=>x.date)))].sort();selectedDate=dates.at(-1)||j.updated_at?.slice(0,10)||new Date().toISOString().slice(0,10);$('updated').textContent=`資料更新：${j.updated_at||selectedDate}`;radar()}catch(e){$('content').innerHTML=`<div class="card errorbox">❌ 資料載入失敗：${esc(e.message)}<br><small>請重新整理；若仍失敗，檢查 GitHub Actions 是否成功部署 data/latest.json。</small></div>`;$('updated').textContent='資料載入失敗'}}
function start(){shell();loadData()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();