(() => {
  'use strict';
  const API='https://api.finmindtrade.com/api/v4/data';
  const WATCH_KEY='kaiV4WatchlistV1', CUSTOM_KEY='kaiV4CustomListV1', CACHE_KEY='kaiV4CustomCacheV1';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const get=(k,def=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(def))}catch{return def}};
  const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const watch=()=>get(WATCH_KEY,[]);
  const saveWatch=a=>put(WATCH_KEY,[...new Set(a.map(String))].slice(0,50));
  const custom=()=>get(CUSTOM_KEY,[]);
  const saveCustom=a=>put(CUSTOM_KEY,[...new Map(a.map(x=>[String(x.id),x])).values()].slice(0,50));
  const cache=()=>get(CACHE_KEY,{});
  async function api(params){const r=await fetch(API+'?'+new URLSearchParams(params),{cache:'no-store'});if(!r.ok)throw Error(`FinMind HTTP ${r.status}`);const j=await r.json();if(j.status&&j.status!==200)throw Error(j.msg||'FinMind API error');return j.data||[]}
  async function resolveName(q){q=String(q||'').trim();if(!q)return null;const info=await api({dataset:'TaiwanStockInfo'});const hit=info.find(x=>String(x.stock_id||x.id)===q)||info.find(x=>String(x.stock_name||x.name||'').trim()===q)||info.find(x=>String(x.stock_name||x.name||'').includes(q));if(!hit)return null;return{id:String(hit.stock_id||hit.id),name:String(hit.stock_name||hit.name||q)}}
  function addWatch(id,name){id=String(id);if(!/^\d{4,6}$/.test(id))return false;saveWatch([...watch(),id]);if(name){const a=custom(),c=a.find(x=>String(x.id)===id);if(c){c.name=name;saveCustom(a)}}return true}
  function diagnosisAddButton(){const head=document.querySelector('.diagnose-head');if(!head||head.querySelector('[data-fix-watch]'))return;const small=head.querySelector('h2 small'),id=small?.textContent?.trim();if(!id)return;const h2=head.querySelector('h2');const name=(h2?.childNodes?.[0]?.textContent||'').replace(/^🔬\s*/,'').trim()||id;const btn=document.createElement('button');btn.dataset.fixWatch='1';btn.style.marginTop='12px';const active=watch().includes(id);btn.textContent=active?'★ 已加入觀察名單':'☆ 加入觀察名單';btn.onclick=()=>{addWatch(id,name);btn.textContent='★ 已加入觀察名單'};const anchor=head.querySelector('.tag')||head.querySelector('.bigprice');if(anchor)anchor.insertAdjacentElement('afterend',btn);else head.firstElementChild?.appendChild(btn)}
  let repairingNames=false;
  function repairCustomNames(){if(repairingNames)return;const list=custom(),bad=list.filter(x=>/^\d{4,6}$/.test(String(x.name||''))||!x.name);if(!bad.length)return;repairingNames=true;Promise.all(bad.map(async x=>{try{const r=await resolveName(x.id);return r?{...x,name:r.name}:x}catch{return x}})).then(repaired=>{const m=new Map(list.map(x=>[String(x.id),x]));repaired.forEach(x=>m.set(String(x.id),x));saveCustom([...m.values()]);const box=$('customList');if(box&&document.querySelector('#customInput'))renderCustomCards(box)}).finally(()=>{repairingNames=false})}
  function renderCustomCards(box){const list=custom(),c=cache(),data=list.map(s=>c[String(s.id)]?.data).filter(Boolean);if(!data.length){box.innerHTML='<div class="loading">尚未有分析快取，請按「全部更新」。</div>';return}const pct=v=>v==null?'-':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`,n=(v,d=1)=>v==null||Number.isNaN(Number(v))?'-':Number(v).toLocaleString(undefined,{maximumFractionDigits:d}),net=v=>v==null?'-':`${Number(v)>=0?'+':''}${(Number(v)/1e8).toFixed(2)}億`,sig=s=>({'偏多／可研究':'🟢 偏多／可研究','等待站回20MA':'🟡 等待站回20MA','過熱':'🟠 過熱','超跌觀察':'🔵 超跌觀察','不追高':'🔴 不追高','中性':'⚪ 中性'}[s]||'⚪ 中性');const headers=['結論','股票','代號','類別','最新價','漲跌%','評分','產業','基本面','估值','籌碼','技術','PE','EPS','月營收','YoY','外資20日','投信20日','法人20日','MA5','MA20','MA60','距20MA','RSI','MACD柱','量比','管理'];const rows=data.map(x=>`<tr><td>${sig(x.technical_signal)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.id)}</td><td>${esc(x.category||'自選股')}</td><td>${n(x.price)}</td><td>${pct(x.pct)}</td><td><b>${n(x.score,0)}</b></td><td>${n(x.industry_score,0)}</td><td>${n(x.fundamental_score,0)}</td><td>${n(x.valuation_score,0)}</td><td>${n(x.chips_score,0)}</td><td>${n(x.technical_score,0)}</td><td>${n(x.pe,2)}</td><td>${n(x.eps_ttm,2)}</td><td>${x.revenue==null?'-':n(x.revenue/1e8,2)+'億'}</td><td>${pct(x.revenue_yoy)}</td><td>${net(x.foreign_20d_net)}</td><td>${net(x.trust_20d_net)}</td><td>${net(x.institution_20d_net)}</td><td>${n(x.ma5,2)}</td><td>${n(x.ma20,2)}</td><td>${n(x.ma60,2)}</td><td>${pct(x.ma20_gap_pct)}</td><td>${n(x.rsi14,1)}</td><td>${n(x.macd_hist,3)}</td><td>${x.volume_ratio_5d_20d==null?'-':n(x.volume_ratio_5d_20d,2)+'x'}</td><td><button class="mini" data-fix-remove="${esc(x.id)}">移除</button></td></tr>`).join('');box.innerHTML=`<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;box.querySelectorAll('[data-fix-remove]').forEach(b=>b.onclick=()=>{saveCustom(list.filter(x=>String(x.id)!==String(b.dataset.fixRemove)));saveWatch(watch().filter(x=>String(x)!==String(b.dataset.fixRemove)));renderCustomCards(box)})}
  function repairCustomPage(){const input=$('customInput'),oldBtn=$('customAdd');if(!input||!oldBtn||oldBtn.dataset.fixBound)return;oldBtn.dataset.fixBound='1';const legacy=oldBtn,btn=legacy.cloneNode(true);legacy.replaceWith(btn);btn.dataset.fixBound='1';btn.onclick=async()=>{const q=input.value.trim();if(!q)return;try{btn.disabled=true;btn.textContent='確認股票…';const r=await resolveName(q);if(!r)throw Error('找不到股票，請輸入正確股號或股票名稱');input.value=r.name;legacy.click();setTimeout(repairCustomNames,1200)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='＋ 新增並分析'}};const listBox=$('customList');if(listBox){const originalRefresh=$('customRefresh');if(originalRefresh&&!originalRefresh.dataset.fixRefresh){originalRefresh.dataset.fixRefresh='1';originalRefresh.addEventListener('click',()=>setTimeout(repairCustomNames,1800))}renderCustomCards(listBox)}}
  function watchPageEnhance(){const title=document.querySelector('.hero h2');if(!title||!title.textContent.includes('我的觀察名單'))return;const ids=watch(),list=custom().filter(x=>ids.includes(String(x.id)));if(!list.length)return;const content=$('content');if(content.querySelector('[data-fix-custom-watch]'))return;const c=cache(),data=list.map(x=>c[String(x.id)]?.data).filter(Boolean);if(!data.length)return;const card=document.createElement('div');card.className='card';card.dataset.fixCustomWatch='1';card.innerHTML='<div class="section-head"><h2>⭐ 自選股觀察名單</h2><span class="muted">與核心雷達共用觀察清單</span></div><div class="tablewrap"><table><thead><tr><th>結論</th><th>股票</th><th>代號</th><th>評分</th><th>最新價</th><th>漲跌%</th><th>技術</th><th>PE</th><th>EPS</th><th>營收YoY</th><th>距20MA</th><th>管理</th></tr></thead><tbody></tbody></table></div>';const tbody=card.querySelector('tbody'),pct=v=>v==null?'-':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`,n=(v,d=1)=>v==null||Number.isNaN(Number(v))?'-':Number(v).toLocaleString(undefined,{maximumFractionDigits:d}),sig=s=>({'偏多／可研究':'🟢 偏多／可研究','等待站回20MA':'🟡 等待站回20MA','過熱':'🟠 過熱','超跌觀察':'🔵 超跌觀察','不追高':'🔴 不追高','中性':'⚪ 中性'}[s]||'⚪ 中性');tbody.innerHTML=data.map(x=>`<tr><td>${sig(x.technical_signal)}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.id)}</td><td>${n(x.score,0)}</td><td>${n(x.price)}</td><td>${pct(x.pct)}</td><td>${n(x.technical_score,0)}</td><td>${n(x.pe,2)}</td><td>${n(x.eps_ttm,2)}</td><td>${pct(x.revenue_yoy)}</td><td>${pct(x.ma20_gap_pct)}</td><td><button class="mini" data-fix-watch-remove="${esc(x.id)}">移除</button></td></tr>`).join('');content.appendChild(card);card.querySelectorAll('[data-fix-watch-remove]').forEach(b=>b.onclick=()=>{saveWatch(watch().filter(id=>String(id)!==String(b.dataset.fixWatchRemove)));card.remove()})}
  const observer=new MutationObserver(()=>{diagnosisAddButton();repairCustomPage();repairCustomNames();watchPageEnhance()});observer.observe(document.body,{subtree:true,childList:true});setTimeout(()=>{diagnosisAddButton();repairCustomPage();repairCustomNames();watchPageEnhance()},500);
})();
